# Generated by Django 5.2.1 on 2025-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNPL', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
